coverage:
  precision: 1
  round: down
  range: "30...100"

  status:
    project:
      default:
        target: 30%
    patch:
      default:
        target: 60%
    changes: no

comment:
  # diff, changes, footer, reach, flags, suggestions
  layout: "header, files"
