# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# Renaming ? Change the README badge.
name: Build Release and Publish

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ANDROID_BUILD_AND_PUBLISH:
    name: Build Release and Publish
    runs-on: ubuntu-latest
    needs: [ ANDROID_UNIT_TESTS, ANDROID_EMULATOR_TESTS ]
    env:
      ARTIFACTORY_URL: https://premise.jfrog.io/premise
      ARTIFACTORY_USERNAME: bot-travis-ci
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Assemble release and publish
        run: ./gradlew cameraview:assembleRelease artifactoryPublish --stacktrace
  ANDROID_UNIT_TESTS:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Execute unit tests
        run: ./gradlew cameraview:runUnitTests --stacktrace

  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        EMULATOR_API: [22]
        include:
          - EMULATOR_API: 22
            EMULATOR_ARCH: x86
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Execute emulator tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2.21.0
        with:
          api-level: ${{ matrix.EMULATOR_API }}
          arch: ${{ matrix.EMULATOR_ARCH }}
          disable-animations: true
          profile: Nexus 5X
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back emulated -camera-front emulated -gpu swiftshader_indirect
          script: ./.github/workflows/emulator_script.sh